### PR TITLE
Moved home page

### PR DESCRIPTION
**Pull request by kshitij01042002**
Moved the content of the page as requested 
Issue No. #8

### CODE REVIEW

**Comment by Anurag-Deo** [comment]
Add a little margin between the hero section and the about section

**Comment by kshitij01042002** [comment]
Done!

**Comment by Anurag-Deo** [comment]
Last one more thing, instead of clubs in IITP, add "About Student's Gymkhana" (gymkhana under the lime shade). Also, adjust its font size so that they all fit in one line

**Comment by Anurag-Deo** [comment]
Great Work

**Pull request merged**
